name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  actions: read

jobs:
  build:
    strategy:
      matrix:
        sdk_version: [31, 32, 33]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK ${{ matrix.sdk_version }}
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.sdk_version }}
          target: android-${{ matrix.sdk_version }}
          ndk: 23.1.7779620

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
