name: Publish Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write
  actions: read

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Clean Build Directory
        run: ./gradlew clean

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/docs/javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN as an environment variable