name: Publish Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Allows writing documentation files to GitHub Pages
  actions: read    # Grants access to reusable actions

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/javadoc
