name: Release Creation

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required for creating a release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Update Version in build.gradle
        run: |
          VERSION=${{ github.ref_name }}
          sed -i "s/versionName \".*\"/versionName \"$VERSION\"/" app/build.gradle
          sed -i "s/versionCode .*/versionCode $(echo $VERSION | tr -d 'v' | tr '.' ' ' | awk '{print $1*100 + $2*10 + $3}')/" app/build.gradle

      - name: Build
        run: ./gradlew assembleRelease

      - name: Generate Changelog
        id: changelog
        run: |
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --oneline > CHANGELOG.md
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changelog:
            ${{ env.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk