name: Release Creation

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Allows creating and uploading releases
  actions: read    # Grants access to reusable actions
  packages: write  # Required to upload release packages (e.g., APK files)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        run: ./gradlew assembleRelease

      - name: Generate Changelog
        id: changelog
        run: git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --oneline > CHANGELOG.md

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
